name : microservices-dev

services:
  # PostgreSQL para User Service
  postgres-product-dev:
    image: postgres:15-alpine
    container_name: postgres-product-dev
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    ##ports:
    ##  - "5433:5433"
    volumes:
      - postgres-product-dev-data:/var/lib/postgresql/data
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d productdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  #  Product Service
  product-service-dev:
    image: product-service-dev:1.0
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "9082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-product-dev:5432/productdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres-product-dev:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

networks:
  microservice-network:
    driver: bridge
volumes:
  postgres-product-dev-data:
    driver: local